# Generated by Django 3.0.8 on 2022-01-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=10)),
                ('School', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.StudentInfo')),
            ],
        ),
    ]
