# Generated by Django 3.0.8 on 2022-01-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='Mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
