# Generated by Django 3.0.8 on 2022-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_auto_20220112_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='School',
            field=models.CharField(max_length=30),
        ),
    ]
